### ISSUE TITLE
could we have some clarification on prefixes please ? 

### ISSUE THREAD

**Issue by PeterScream** [fasteddy516/SimplMQTT#12]
the  1R; , 0X; xx;

seems like a very solid module, good job!

**Comment by fasteddy516** [comment]
Documentation is on my list (along with a couple of other minor items), but I've got to find the time to do it.

As far as the topic prefixes go, they are loosely-matched 3-character values used to specify MQTT QoS and retain settings as follows:

* **1st character:** Determines the QoS level at which to _subscribe_ to the corresponding topic.  Use `0` for QoS0 or `1` for QoS1.  Use any other character (I recommend `x`) if you do not wish to subscribe to the topic.  (This is useful for topics that you only need to publish to).  MQTT QoS is explained [here](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/).  Note that SimplMQTT does *not* support QoS2.

* **2nd character:** Set to `R` (or `r`) to enable message retention for the corresponding topic.  Use any other character (I recommend `x`) to disable message retention.  MQTT message retention is explained [here](https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/).

* **3rd character:** This is just a separator between the MQTT settings and actual Topic field.  It can be any character, but I recommend (and use) a semicolon.

Examples:

`0R;awesome_topic` = subscribe to `awesome_topic` at QoS0 and enable message retention for publishing
`1x;another_topic` = subscribe to `another_topic` at QoS1 with no message retention for publishing
`xR;publish_me` = do not subscribe to the `publish_me` topic, enable message retention for publishing

Hope that helps!
