### ISSUE TITLE
Problem opening the project and the library

### ISSUE THREAD

**Issue by OZEO-DOOZ** [fasteddy516/SimplMQTT#14]
Hi,

I cannot open the demo project. The project seems empty. 
Even for the library, I cannot find it in simpl. 

What is the procedure to open it?

**Comment by michisutter** [comment]
I have the same problem

**Comment by fasteddy516** [comment]
Sorry for the confusion - the download currently in the 'releases' section is just the Simpl# CLZ file.  The SIMPL Windows demo files have to be downloaded from GitHub separately.  The next release will include all of the SIMPL Windows demo files.
