### ISSUE TITLE
Can't compile, missing library

### ISSUE THREAD

**Issue by ZacharieGignac** [fasteddy516/SimplMQTT#16]
Missing library when compiling, ConsoleServiceBase.dll

**Comment by fasteddy516** [comment]
I ran into this as well - recompiling the `.clz` file in Visual Studio 2008 (without making any other changes) solved it for me.  I'll update the .clz here on GitHub shortly, after some testing.

**Comment by fasteddy516** [comment]
I've updated the files on the release page and added a link to a download for the full SIMPL Windows demo project.  Everything compiles fine on my end now (using the software versions listed on the release page).
